services:
  - type: web
    name: mymonitorxx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEV_MODE
        value: "false"
      - key: DATABASE_NAME
        value: mymonitorxx
      - key: MONGODB_URI
        sync: false
